### PR TITLE
Implement #8: configurable logging to console

### PR DESCRIPTION
**Pull request by leonard84**
This implementation supports both modes of operation mentioned in #8, by default it logs to debug but this can be changed to info-level via property.

### CODE REVIEW

**Comment by leonard84** [comment]
@timgifford could you please release a new version, its the one thing that blocks the use in our larger projects.

**Comment by timgifford** [comment]
I'll create a new release this weekend.

**Comment by leonard84** [comment]
@timgifford great, thanks

**Comment by timgifford** [comment]
@leonard84 It's out there!

**Pull request merged**
