### PR TITLE
Added ability to collect and log project durations.

### PR DESCRIPTION
**Pull request by zebrafive**

### CODE REVIEW

**Comment by zebrafive** [comment]
Pull request adds project durations to log output, and sorts projects in order of start time.

**Comment by zebrafive** [comment]
Please check out, test and then merge my pull request (if this is something you want to include). I'm not sure what Travis CI is complaining about, but I did build and test it.

**Comment by mithuns** [comment]
Just add this to the travis.yml file
```
before_install:
  - chmod +x mvnw
```
Before `install: true  `

**Comment by timgifford** [comment]
I published v3.0.3 to the central repository that includes these changes.

**Pull request merged**
