### PR TITLE
Add mvn wrapper to use Maven 3.3.9, Fix documentation ...

### PR DESCRIPTION
**Pull request by leonard84**
-Fix documentation: the filename was incorrect, extensions.xml is the
                    correct one
                    added note about minimal Maven Version
-Extended integration tests to output maven version
-Extended Tavis to test both jdk7 and jdk8
-Use contains instead of complete match for csv-lines, since
 Java collection ordering changed between java 7 and 8

### CODE REVIEW

**Comment by leonard84** [comment]
@timgifford this should fix it

**Comment by timgifford** [comment]
I don't like the idea of including binaries. 

Could we include the plugin and remove the generated files. We also should add line to .gitignore for the maven-wrapper so we don't accidentally add back to git.
```
            <plugin>
                <groupId>com.rimerosolutions.maven.plugins</groupId>
                <artifactId>wrapper-maven-plugin</artifactId>
                <version>0.0.4</version>
                <inherited>false</inherited>
                <configuration>
                    <mavenVersion>3.3.9</mavenVersion>
                </configuration>
            </plugin>
```

Then have travis run `mvn wrapper:wrapper && ./mvnw install `

**Comment by timgifford** [comment]
Nevermind. Merged in. Next up is publishing a release.

**Comment by leonard84** [comment]
I understand the dislike for binaries in scm, however I think that maven wrapper/gradle wrapper are a valid exception, since they remove the need to have maven installed at all.

**Comment by timgifford** [comment]
Agreed. After some thought and learning I changed my opinion. Merged in and release v3.0.0 yesterday.

**Pull request merged**
