### PR TITLE
Implemented simple csv output

### PR DESCRIPTION
**Pull request by leonard84**
Implemented simple csv output
and use fixed locale for output

Proposed implementation for Issue  #11

### CODE REVIEW

**Comment by leonard84** [comment]
@timgifford any problems with this PR?

**Comment by timgifford** [comment]
I appreciate your pull requests. Thanks again.

I've rejected previous requests to publish the metics to other formats. You're request has me looking into this again. My fear the need for properties for every output format (an their required variables) will complicate the usage of the extension.

So far I've had requests for these formats:
 * statsd
 * CSV
 * Influxdb

I think this would be a great feature and I am looking for a way to specify a publishing implementation in the POM and pass required configuration with it. The hooks for timing are only available in the Extensions, but I can't provide dependencies or configuration in the <extension> section. My current thinking is to follow a similar model as Maven Wagon (http://maven.apache.org/wagon/). The extension would be a specific implementation and a plugin to provide the configuration.

I'm open to ideas and suggestions.

**Comment by leonard84** [comment]
Hi Tim,

thanks for the explanation and I understand your concerns. I don't know the Maven Wagon model so I can't really comment on the complexities. My approach would be to have a default canonical format in the core extension, be it CSV, JSON, XML, statsd or something else. It should be easy to write to and convert from without sacrificing information and performance. This way you could run an additional transformation step later on into other formats.

We currently have a multi-module project with 47 modules and 10+ mojos are executed for each so we definitely need a structured output format.

I picked CSV since it is dead simple and can easily be imported into excel to perform complex analyses.

**Comment by leonard84** [comment]
@timgifford what about using this approach for now, and if there are more output formats available later on we can refactor. I would recommend the KISS approach here, I've seen it to often that features were planned to big and thus were never completed.

**Comment by timgifford** [comment]
That's fair. I'll pull it in.

**Pull request merged**
